- hosts: localhost
  connection: local
  gather_facts: no
  sudo: no
  vars:
    homebrew_taps:
      - homebrew/binary
      - homebrew/dupes
      - caskroom/cask
      - sanemat/font
    homebrew_packages:
      - { name: readline }
      - { name: openssl }
      - { name: openssl, state: linked, install_options: force }
      - { name: coreutils }
      - { name: cmake }
      - { name: autoconf }
      - { name: automake }
      - { name: python }
      - { name: ansible }
      - { name: git }
      - { name: curl }
      - { name: wget }
      - { name: pkg-config }
      - { name: nkf }
      - { name: jq }
      - { name: rbenv }
      - { name: ruby-build }
      - { name: ssh-copy-id }
      - { name: sqlite }
      - { name: tmux }
      - { name: reattach-to-user-namespace }
      - { name: ctags }
      - { name: xz }
      - { name: imagemagick }
      - { name: autojump }
      - { name: source-highlight }
      - { name: go }
      - { name: direnv }
      - { name: peco }
      - { name: hub }
      - { name: tig }
      - { name: zsh, install_options: disable-etcdir }
      - { name: flow }
      - { name: docker }
      - { name: docker-machine }
      - { name: docker-compose }
    homebrew_cask_packages:
      - { name: java }
      - { name: adobe-reader }
      - { name: google-chrome }
      - { name: google-japanese-ime }
      - { name: iterm2 }
      - { name: skype }
      - { name: slack }
      - { name: karabiner }
      - { name: seil }
      - { name: flux } # ブルーライトをカットするらしい
      - { name: skitch }
      - { name: evernote }
      - { name: seashore }
      - { name: vagrant }
      - { name: virtualbox }
      - { name: alfred }
    plist_buddy_items:
      - { target: ~/Library/Preferences/com.googlecode.iterm2.plist, command: 'Set :"New Bookmarks":0:"Normal Font" "Ricty 14"' }
      - { target: ~/Library/Preferences/com.googlecode.iterm2.plist, command: 'Set :"New Bookmarks":0:"Non Ascii Font" "Ricty 14"' }
      - { target: ~/Library/Preferences/com.googlecode.iterm2.plist, command: 'Set :"New Bookmarks":0:"Transparency" 0.122797' }
      - { target: ~/Library/Preferences/com.googlecode.iterm2.plist, command: 'Set :"New Bookmarks":0:"Silence Bell" true' }
      - { target: ~/Library/Preferences/com.googlecode.iterm2.plist, command: 'Set :"New Bookmarks":0:"Use Bold Font" false' }

  tasks:
    - name: homebrew の tap リポジトリを追加
      homebrew_tap: tap={{ item }} state=present
      with_items: homebrew_taps

    - name: homebrew をアップデート
      homebrew: update_homebrew=yes

    # brew
    - name: brew パッケージをインストール
      homebrew: >
        name={{ item.name }}
        state={{ item.state | default('latest') }}
        install_options={{
          item.install_options | default() | join(',')
          if item.install_options is not string
          else item.install_options
        }}
      with_items: homebrew_packages
      register: brew_result
    - name: brew パッケージの情報保存先ディレクトリを作成
      file: path=brew_info state=directory
    - name: brew パッケージの情報を保存
      shell: brew info {{ item }} > brew_info/{{ item }}
      with_items: brew_result.results | selectattr('changed') | map(attribute='item') | map(attribute='name') | list

    # cask
    - name: homebrew-cask のインストール
      homebrew: name=brew-cask state=latest
    - name: cask パッケージをインストール
      homebrew_cask: name={{ item.name }} state={{ item.state|default('installed') }}
      with_items: homebrew_cask_packages
      register: cask_result
    - name: cask パッケージの情報保存先ディレクトリを作成
      file: path=cask_info state=directory
    - name: cask パッケージの情報を保存
      shell: brew cask info {{ item }} > cask_info/{{ item }}
      with_items: cask_result.results | selectattr('changed') | map(attribute='item') | map(attribute='name') | list

    # oh-my-zsh
    - name: oh-my-zsh のインストール
      shell: curl -L https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh | sh
      args:
        creates: ~/.oh-my-zsh/

    # nodebrew
    - name: nodebrew をインストール
      shell: curl -L git.io/nodebrew | perl - setup
      args:
        creates: ~/.nodebrew/

    # Ricty
    - name: xquartz のインストール (for Ricty)
      homebrew_cask: name=xquartz
    - name: fontforge のインストール (for Ricty)
      homebrew: name=fontforge
    - name: Recty のインストール
      homebrew: name=ricty install_options=powerline,vim-powerline
    - name: 生成されたフォントファイルをコピー
      shell: cp -f $(brew --cellar ricty)/*/share/fonts/Ricty*.ttf ~/Library/Fonts/
      args:
        creates: ~/Library/Fonts/Ricty-Bold.ttf
      notify: run fc-cache

    # dotfiles
    - name: dotfiles のインストール
      shell: curl -fsSL https://raw.githubusercontent.com/myamamoto88/dotfiles/master/install.sh | bash

    # vim plugin
    - name: NeoBundle をインストール
      shell: curl -fsSL https://raw.githubusercontent.com/Shougo/neobundle.vim/master/bin/install.sh | bash

    # setting
    - name: PlistBuddy でアプリケーションの設定
      shell: /usr/libexec/PlistBuddy -c '{{ item.command }}' {{ item.target }}
      with_items: plist_buddy_items
    - name: リピートキー設定
      shell: defaults write NSGlobalDomain KeyRepeat -int 3
    - name: リピート入力認識時間の設定
      shell: defaults write NSGlobalDomain InitialKeyRepeat -int 15

  handlers:
    - name: run fc-cache
      shell: fc-cache -vf
